CREATE VIEW VIEW_LIVE_INFORMATION (USER_ID,FIRST_NAME,LAST_NAME,YEAR_OF_BIRTH,MONTH_OF_BIRTH,DAY_OF_BIRTH,GENDER,HOMETOWN_CITY,HOMETOWN_STATE,
HOMETOWN_COUNTRY,CURRENT_CITY,CURRENT_STATE,CURRENT_COUNTRY)
 AS SELECT U.USER_ID,U.FIRST_NAME,U.LAST_NAME,U.YEAR_OF_BIRTH,U.MONTH_OF_BIRTH,
U.DATE_OF_BIRTH,U.GENDER,L.CITY,L.STATE,L.COUNTRY,M.CITY,M.STATE,M.COUNTRY
FROM USER_INFOR U,HOMETOWN_LOCATION H,LOCATION L,LOCATION M,CURRENT_LOCATION C
WHERE (U.USER_ID=H.USER_ID)
AND(U.USER_ID=C.USER_ID)
AND(H.LOCATION_ID=L.LOCATION_ID)
AND(C.LOCATION_ID=M.LOCATION_ID);

CREATE VIEW VIEW_ATTENDED_INFORMATION
(USER_ID,INSTITUTION_NAME,PROGRAM_YEAR,PROGRAM_CONCENTRATION,PROGRAM_DEGREE)
AS SELECT A.USER_ID,C.INSTITUTION_NAME,A.GRADUATION_YEAR,C.CONCENTRATION,C.DEGREE
FROM ATTENDED A,COLLEGE_PROGRAM C
WHERE C.PROGRAM_ID=A.PROGRAM_ID;


CREATE VIEW VIEW_USER_INFORMATION
AS
SELECT L.USER_ID,L.FIRST_NAME,L.LAST_NAME,L.YEAR_OF_BIRTH,L.MONTH_OF_BIRTH,L.DAY_OF_BIRTH,L.GENDER ,L.CURRENT_CITY,L.CURRENT_STATE,L.CURRENT_COUNTRY,L.HOMETOWN_CITY,L.HOMETOWN_STATE,L.HOMETOWN_COUNTRY,A.INSTITUTION_NAME,A.PROGRAM_YEAR,A.PROGRAM_CONCENTRATION,A.PROGRAM_DEGREE
FROM VIEW_LIVE_INFORMATION L
FULL OUTER JOIN VIEW_ATTENDED_INFORMATION A
ON L.USER_ID=A.USER_ID;


CREATE VIEW VIEW_ARE_FRIENDS(USER1_ID,USER2_ID) AS
SELECT * FROM FRIEND_OF;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT A.ALBUM_ID, A.OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME,
    A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK,
    A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATE_TIME,
    P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUM_BELONG A, PHOTO P
WHERE P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME,
    TAG_X_COORDINATE, TAG_Y_COORDINATE
FROM TAG;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE,
    E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE,
    E.EVENT_LOCATION, L.CITY, L.STATE, L.COUNTRY, E.EVENT_START_TIME,
    E.EVENT_END_TIME
FROM EVENT E, LOCATION L, EVENT_AT A
WHERE E.EVENT_ID = A.EVENT_ID AND A.LOCATION_ID = L.LOCATION_ID;
